global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'status-tracking-app'
    static_configs:
      - targets: ['app:8085']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s